server:
  image: node:7
  command: npm start
  working_dir: /app
  volumes:
    - .:/app
  environment:
    PORT: 3000

  ports:
    - "3000:3000"
  links:
      - db
db:
  image: postgres
  expose:
    - 5432
  volumes:
    - ./table_tennis.sql:/docker-entrypoint-initdb.d/table_tennis.sql
    - ./zseeds.sql:/docker-entrypoint-initdb.d/zseeds.sql
  environment:
    POSTGRES_PASSWORD: password
    POSTGRES_USER: user
    POSTGRES_DB: react_table_tennis